import LessonLayout from '../../components/LessonLayout';
import CodeBlock from '../../components/CodeBlock';

export const metadata = {
  title: 'Text Search Types - PostgreSQL Learning',
  description: 'Learn about PostgreSQL text search types including tsvector and tsquery',
};

export default function TextSearchTypes() {
  return (
    <LessonLayout>
      <div className="prose prose-lg dark:prose-invert max-w-none">
        <h1 className="text-4xl font-bold mb-6">Text Search Types</h1>
        
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Text Search Overview</h2>
          <p className="mb-4">
            PostgreSQL provides full-text search capabilities through TSVECTOR and TSQUERY types.
          </p>
          
          <div className="bg-zinc-100 dark:bg-zinc-800 p-4 rounded-lg mb-4">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b">
                  <th className="text-left p-2">Type</th>
                  <th className="text-left p-2">Description</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b"><td className="p-2"><code>TSVECTOR</code></td><td className="p-2">Normalized document (sorted list of lexemes)</td></tr>
                <tr><td className="p-2"><code>TSQUERY</code></td><td className="p-2">Search query with boolean operators</td></tr>
              </tbody>
            </table>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">TSVECTOR Type</h2>
          <p className="mb-4">
            TSVECTOR stores a normalized document as a sorted list of lexemes (words).
          </p>

          <CodeBlock
            title="SQL: TSVECTOR Type"
            language="sql"
            code={`-- Create table with TSVECTOR
CREATE TABLE documents (
  id SERIAL PRIMARY KEY,
  title VARCHAR(200),
  content TEXT,
  search_vector TSVECTOR
);

-- Convert text to TSVECTOR
SELECT to_tsvector('english', 'The quick brown fox jumps over the lazy dog');
-- Result: 'brown':3 'dog':9 'fox':4 'jump':5 'lazi':8 'quick':2

-- Insert with TSVECTOR
INSERT INTO documents (title, content, search_vector)
VALUES 
  ('PostgreSQL Guide', 'PostgreSQL is a powerful database', 
   to_tsvector('english', 'PostgreSQL is a powerful database')),
  ('SQL Tutorial', 'Learn SQL and database management', 
   to_tsvector('english', 'Learn SQL and database management'));

-- Auto-update TSVECTOR with trigger
CREATE OR REPLACE FUNCTION update_search_vector()
RETURNS TRIGGER AS $$
BEGIN
  NEW.search_vector := to_tsvector('english', COALESCE(NEW.title, '') || ' ' || COALESCE(NEW.content, ''));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_documents_search_vector
BEFORE INSERT OR UPDATE ON documents
FOR EACH ROW EXECUTE FUNCTION update_search_vector();

-- Query TSVECTOR
SELECT 
  title,
  search_vector,
  array_length(tsvector_to_array(search_vector), 1) AS word_count
FROM documents;`}
          />
          <CodeBlock
            title="Prisma: TSVECTOR Type"
            language="prisma"
            code={`// schema.prisma
// Prisma doesn't have native TSVECTOR support
// Use String or handle with triggers

model Document {
  id          Int      @id @default(autoincrement())
  title       String   @db.VarChar(200)
  content     String   @db.Text
  searchVector String? @map("search_vector") @db.TsVector
  
  @@map("documents")
}

// Create trigger manually for auto-update
await prisma.$executeRaw\`
  CREATE OR REPLACE FUNCTION update_search_vector()
  RETURNS TRIGGER AS $$
  BEGIN
    NEW.search_vector := to_tsvector('english', COALESCE(NEW.title, '') || ' ' || COALESCE(NEW.content, ''));
    RETURN NEW;
  END;
  $$ LANGUAGE plpgsql
\`;

await prisma.$executeRaw\`
  CREATE TRIGGER update_documents_search_vector
  BEFORE INSERT OR UPDATE ON documents
  FOR EACH ROW EXECUTE FUNCTION update_search_vector()
\`;

// Usage
const document = await prisma.document.create({
  data: {
    title: 'PostgreSQL Guide',
    content: 'PostgreSQL is a powerful database',
    // search_vector is auto-generated by trigger
  },
});

// Query TSVECTOR
const docs = await prisma.$queryRaw\`
  SELECT 
    title,
    search_vector,
    array_length(tsvector_to_array(search_vector), 1) AS word_count
  FROM documents
\`;`}
          />
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">TSQUERY Type</h2>
          <p className="mb-4">
            TSQUERY stores a search query with boolean operators.
          </p>

          <CodeBlock
            title="SQL: TSQUERY Type"
            language="sql"
            code={`-- Convert text to TSQUERY
SELECT to_tsquery('english', 'postgresql & database');
SELECT to_tsquery('english', 'postgresql | sql');
SELECT to_tsquery('english', '!mysql');

-- TSQUERY operators
-- & (AND), | (OR), ! (NOT), <-> (followed by)

-- Search examples
SELECT * FROM documents
WHERE search_vector @@ to_tsquery('english', 'postgresql & database');

SELECT * FROM documents
WHERE search_vector @@ to_tsquery('english', 'postgresql | sql');

SELECT * FROM documents
WHERE search_vector @@ to_tsquery('english', '!mysql');

-- Phrase search
SELECT * FROM documents
WHERE search_vector @@ to_tsquery('english', 'postgresql <-> database');

-- Plain text search (auto-converts to tsquery)
SELECT * FROM documents
WHERE search_vector @@ plainto_tsquery('english', 'postgresql database');

-- Full text search with ranking
SELECT 
  title,
  content,
  ts_rank(search_vector, to_tsquery('english', 'postgresql')) AS rank
FROM documents
WHERE search_vector @@ to_tsquery('english', 'postgresql')
ORDER BY rank DESC;`}
          />
          <CodeBlock
            title="Prisma: TSQUERY Type"
            language="javascript"
            code={`// Use raw SQL for full-text search

// Search with TSQUERY
const results = await prisma.$queryRaw\`
  SELECT 
    id,
    title,
    content,
    ts_rank(search_vector, to_tsquery('english', 'postgresql')) AS rank
  FROM documents
  WHERE search_vector @@ to_tsquery('english', 'postgresql')
  ORDER BY rank DESC
\`;

// Plain text search
const plainResults = await prisma.$queryRaw\`
  SELECT * FROM documents
  WHERE search_vector @@ plainto_tsquery('english', $1)
\`;

// Complex search
const complexResults = await prisma.$queryRaw\`
  SELECT * FROM documents
  WHERE search_vector @@ to_tsquery('english', 'postgresql & (database | sql)')
\`;`}
          />
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Full-Text Search Functions</h2>

          <CodeBlock
            title="SQL: Text Search Functions"
            language="sql"
            code={`-- Ranking functions
SELECT 
  title,
  ts_rank(search_vector, to_tsquery('english', 'postgresql')) AS rank,
  ts_rank_cd(search_vector, to_tsquery('english', 'postgresql')) AS rank_cd
FROM documents
WHERE search_vector @@ to_tsquery('english', 'postgresql')
ORDER BY rank DESC;

-- Highlight matches
SELECT 
  title,
  ts_headline('english', content, to_tsquery('english', 'postgresql')) AS headline
FROM documents
WHERE search_vector @@ to_tsquery('english', 'postgresql');

-- Get matching positions
SELECT 
  title,
  tsvector_to_array(search_vector) AS words,
  ts_stat('SELECT search_vector FROM documents') AS statistics
FROM documents
LIMIT 1;

-- Text search configuration
SELECT * FROM pg_ts_config;

-- Set default text search config
SET default_text_search_config = 'english';

-- Use different languages
SELECT to_tsvector('spanish', 'El rápido zorro marrón');
SELECT to_tsvector('french', 'Le renard brun rapide');`}
          />
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Full-Text Search Indexes</h2>

          <CodeBlock
            title="SQL: GIN Index for Full-Text Search"
            language="sql"
            code={`-- Create GIN index on TSVECTOR
CREATE INDEX idx_documents_search ON documents USING GIN (search_vector);

-- Query using index
EXPLAIN SELECT * FROM documents
WHERE search_vector @@ to_tsquery('english', 'postgresql');

-- Composite index with ranking
CREATE INDEX idx_documents_search_rank ON documents 
USING GIN (search_vector) 
INCLUDE (title, content);`}
          />
        </section>
      </div>
    </LessonLayout>
  );
}

